from __future__ import annotations

from typing import List

from renpy_node_editor.core.model import Project, Scene, Block, BlockType

INDENT = "    "


def _gen_label(scene: Scene) -> str:
    return f"label {scene.label}:\n"


def _gen_say(block: Block, indent: str) -> str:
    who = block.params.get("who", "")
    text = block.params.get("text", "")
    if who:
        return f"{indent}{who} \"{text}\"\n"
    return f"{indent}\"{text}\"\n"


def _gen_menu(block: Block, indent: str) -> str:
    """
    Простейший menu:
    block.params:
      question: str
      choices: List[{"text": str, "jump": str}]
    """
    lines: List[str] = []
    question = block.params.get("question")
    if question:
        lines.append(f"{indent}\"{question}\"\n")

    lines.append(f"{indent}menu:\n")

    choices = block.params.get("choices", []) or []
    for choice in choices:
        text = choice.get("text", "")
        jump = choice.get("jump", "")
        lines.append(f"{indent}{INDENT}\"{text}\":\n")
        if jump:
            lines.append(f"{indent}{INDENT*2}jump {jump}\n")

    return "".join(lines)


def _gen_jump(block: Block, indent: str) -> str:
    target = block.params.get("target", "")
    if not target:
        return ""
    return f"{indent}jump {target}\n"


def _gen_scene(block: Block, indent: str) -> str:
    bg = block.params.get("background", "black")
    trans = block.params.get("transition")
    line = f"{indent}scene {bg}"
    if trans:
        line += f" with {trans}"
    return line + "\n"


def _gen_show(block: Block, indent: str) -> str:
    who = block.params.get("character", "")
    expr = block.params.get("expression", "")
    at = block.params.get("at", "")
    parts = [who]
    if expr:
        parts.append(expr)
    line = f"{indent}show {' '.join(parts)}"
    if at:
        line += f" at {at}"
    return line + "\n"


def _generate_block(block: Block, indent: str) -> str:
    if block.type is BlockType.SAY:
        return _gen_say(block, indent)
    if block.type is BlockType.MENU:
        return _gen_menu(block, indent)
    if block.type is BlockType.JUMP:
        return _gen_jump(block, indent)
    if block.type is BlockType.SCENE:
        return _gen_scene(block, indent)
    if block.type is BlockType.SHOW:
        return _gen_show(block, indent)
    if block.type is BlockType.LABEL:
        # Внутренний LABEL как отдельный блок
        label = block.params.get("label", "")
        if label:
            return f"label {label}:\n"
    return ""


def _generate_scene(scene: Scene) -> str:
    lines: List[str] = []

    # Заголовок-сцена как label
    lines.append(_gen_label(scene))

    indent = INDENT
    for block in scene.blocks:
        lines.append(_generate_block(block, indent))

    lines.append("\n")
    return "".join(lines)


def generate_renpy_script(project: Project) -> str:
    """
    Сгенерировать полный текст Ren'Py-скрипта для проекта.
    Дальше сюда можно добавлять define, default, стили и т.п.
    """
    lines: List[str] = []

    # Простейший заголовок
    lines.append("# Generated by RenPy Node Editor\n")
    lines.append("define narrator = Character('Narrator')\n\n")

    for scene in project.scenes:
        lines.append(_generate_scene(scene))

    return "".join(lines)
